# Generated by Django 5.0.6 on 2024-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='Email',
        ),
        migrations.AddField(
            model_name='todo',
            name='password',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
