# Generated by Django 5.0.6 on 2024-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
