# Generated by Django 5.0.6 on 2024-05-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_todo_name_alter_todo_email_alter_todo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
